import type { CategoryId, Service } from "@/lib/booking-types";

export const services: Record<CategoryId, Service[]> = {
  peluqueria: [
    {
      id: "corte-fem",
      name: "Corte femenino",
      desc: "Diseño personalizado según rostro y estilo.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$18.000",
      priceAmount: 18000,
      tag: "popular",
    },
    {
      id: "brushing",
      name: "Brushing",
      desc: "Secado con forma y movimiento.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$10.000",
      priceAmount: 10000,
    },
    {
      id: "peinado-diario",
      name: "Peinado diario",
      desc: "Look prolijo para el día a día.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$11.000",
      priceAmount: 11000,
    },
    {
      id: "peinado-social",
      name: "Peinado social",
      desc: "Para reuniones y salidas especiales.",
      duration: "50 min",
      durationMinutes: 50,
      price: "$18.000",
      priceAmount: 18000,
    },
    {
      id: "recogido",
      name: "Recogido",
      desc: "Updo elegante para ocasiones.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$22.000",
      priceAmount: 22000,
      tag: "evento",
    },
    {
      id: "color-global",
      name: "Color global",
      desc: "Color uniforme de raíz a puntas.",
      duration: "1 h 30",
      durationMinutes: 90,
      price: "$32.000",
      priceAmount: 32000,
      tag: "color",
    },
    {
      id: "retoque-raiz",
      name: "Retoque de raíz",
      desc: "Cobertura de crecimiento.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$22.000",
      priceAmount: 22000,
      tag: "color",
    },
    {
      id: "tonalizacion",
      name: "Tonalización",
      desc: "Refresca y unifica el tono.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$16.000",
      priceAmount: 16000,
      tag: "color",
    },
    {
      id: "bano-luz",
      name: "Baño de luz",
      desc: "Brillo y matiz instantáneo.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$14.000",
      priceAmount: 14000,
    },
    {
      id: "mechas",
      name: "Mechas",
      desc: "Iluminación clásica.",
      duration: "2 h",
      durationMinutes: 120,
      price: "$42.000",
      priceAmount: 42000,
      tag: "color",
    },
    {
      id: "babylights",
      name: "Babylights",
      desc: "Mechas finas y naturales.",
      duration: "2 h 30",
      durationMinutes: 150,
      price: "$52.000",
      priceAmount: 52000,
      tag: "popular",
    },
    {
      id: "balayage",
      name: "Balayage",
      desc: "Degradé natural pintado a mano.",
      duration: "3 h",
      durationMinutes: 180,
      price: "$58.000",
      priceAmount: 58000,
      tag: "popular",
    },
    {
      id: "claritos",
      name: "Claritos",
      desc: "Reflejos suaves en zonas clave.",
      duration: "1 h 30",
      durationMinutes: 90,
      price: "$28.000",
      priceAmount: 28000,
    },
    {
      id: "alisado",
      name: "Alisado",
      desc: "Lacio duradero con cuidado capilar.",
      duration: "3 h",
      durationMinutes: 180,
      price: "$65.000",
      priceAmount: 65000,
    },
    {
      id: "botox",
      name: "Botox capilar",
      desc: "Suavidad, brillo y reducción del frizz.",
      duration: "1 h 30",
      durationMinutes: 90,
      price: "$28.000",
      priceAmount: 28000,
      tag: "tratamiento",
    },
    {
      id: "nutricion",
      name: "Nutrición capilar",
      desc: "Aporte de nutrientes profundos.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$15.000",
      priceAmount: 15000,
      tag: "tratamiento",
    },
    {
      id: "hidratacion",
      name: "Hidratación profunda",
      desc: "Recupera elasticidad y brillo.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$15.000",
      priceAmount: 15000,
      tag: "tratamiento",
    },
    {
      id: "reparacion",
      name: "Reparación capilar",
      desc: "Fibras dañadas restauradas.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$20.000",
      priceAmount: 20000,
      tag: "tratamiento",
    },
    {
      id: "reconstruccion",
      name: "Reconstrucción",
      desc: "Plan intensivo para cabellos castigados.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$22.000",
      priceAmount: 22000,
      tag: "tratamiento",
    },
    {
      id: "post-color",
      name: "Tratamiento post-color",
      desc: "Sella y prolonga el color.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$12.000",
      priceAmount: 12000,
      tag: "tratamiento",
    },
    {
      id: "corte-brushing",
      name: "Corte + brushing",
      desc: "Corte con terminación profesional.",
      duration: "1 h 15",
      durationMinutes: 75,
      price: "$25.000",
      priceAmount: 25000,
      tag: "combinado",
    },
    {
      id: "color-nutricion",
      name: "Color + nutrición",
      desc: "Color con tratamiento incluido.",
      duration: "2 h",
      durationMinutes: 120,
      price: "$42.000",
      priceAmount: 42000,
      tag: "combinado",
    },
    {
      id: "mechas-tonalizacion",
      name: "Mechas + tonalización",
      desc: "Iluminación con matiz a medida.",
      duration: "2 h 30",
      durationMinutes: 150,
      price: "$52.000",
      priceAmount: 52000,
      tag: "combinado",
    },
    {
      id: "balayage-nutricion",
      name: "Balayage + nutrición",
      desc: "Degradé con tratamiento.",
      duration: "3 h 30",
      durationMinutes: 210,
      price: "$68.000",
      priceAmount: 68000,
      tag: "combinado",
    },
    {
      id: "alisado-corte",
      name: "Alisado + corte",
      desc: "Lacio con renovación de forma.",
      duration: "3 h 30",
      durationMinutes: 210,
      price: "$72.000",
      priceAmount: 72000,
      tag: "combinado",
    },
    {
      id: "alisado-nutricion",
      name: "Alisado + nutrición",
      desc: "Lacio con cuidado profundo.",
      duration: "3 h 30",
      durationMinutes: 210,
      price: "$72.000",
      priceAmount: 72000,
      tag: "combinado",
    },
    {
      id: "mechas-corte-brushing",
      name: "Mechas + corte + brushing",
      desc: "Pack completo de transformación.",
      duration: "3 h",
      durationMinutes: 180,
      price: "$62.000",
      priceAmount: 62000,
      tag: "combinado",
    },
    {
      id: "color-tratamiento",
      name: "Color + tratamiento reparador",
      desc: "Color con reparación intensiva.",
      duration: "2 h 30",
      durationMinutes: 150,
      price: "$48.000",
      priceAmount: 48000,
      tag: "combinado",
    },
  ],
  maquillaje: [
    {
      id: "mk-social",
      name: "Maquillaje social",
      desc: "Look natural luminoso.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$18.000",
      priceAmount: 18000,
    },
    {
      id: "mk-fiesta",
      name: "Maquillaje de fiesta",
      desc: "Glamour y larga duración.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$24.000",
      priceAmount: 24000,
      tag: "popular",
    },
    {
      id: "mk-evento",
      name: "Maquillaje para eventos",
      desc: "Para invitadas especiales.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$26.000",
      priceAmount: 26000,
      tag: "evento",
    },
    {
      id: "mk-novia",
      name: "Maquillaje de novia",
      desc: "Diseño exclusivo para tu día.",
      duration: "1 h 30",
      durationMinutes: 90,
      price: "$45.000",
      priceAmount: 45000,
      tag: "evento",
    },
    {
      id: "mk-prueba",
      name: "Prueba de maquillaje",
      desc: "Ensayo previo personalizado.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$20.000",
      priceAmount: 20000,
    },
  ],
  unas: [
    {
      id: "semi",
      name: "Esmaltado semipermanente",
      desc: "Color duradero y brillo.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$10.000",
      priceAmount: 10000,
      tag: "popular",
    },
    {
      id: "kapping",
      name: "Kapping",
      desc: "Refuerzo sobre uña natural.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$13.000",
      priceAmount: 13000,
    },
    {
      id: "softgel",
      name: "Soft gel",
      desc: "Extensión liviana y natural.",
      duration: "1 h 30",
      durationMinutes: 90,
      price: "$18.000",
      priceAmount: 18000,
      tag: "popular",
    },
    {
      id: "nailart",
      name: "Nail art",
      desc: "Diseños y detalles a mano.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$5.000",
      priceAmount: 5000,
    },
    {
      id: "mani",
      name: "Manicura completa",
      desc: "Cutícula, forma y prolijidad.",
      duration: "45 min",
      durationMinutes: 45,
      price: "$8.000",
      priceAmount: 8000,
    },
    {
      id: "retiro",
      name: "Retiro y renovación",
      desc: "Quita previa y nuevo color.",
      duration: "1 h",
      durationMinutes: 60,
      price: "$12.000",
      priceAmount: 12000,
    },
  ],
  depilacion: [
    {
      id: "depi-rostro-completo",
      name: "Rostro completo",
      desc: "Depilación facial completa con terminación prolija.",
      duration: "30 min",
      durationMinutes: 30,
      price: "$30.000",
      priceAmount: 30000,
      tag: "popular",
    },
    {
      id: "depi-cejas",
      name: "Cejas",
      desc: "Diseño y limpieza de cejas para enmarcar la mirada.",
      duration: "15 min",
      durationMinutes: 15,
      price: "$12.000",
      priceAmount: 12000,
    },
    {
      id: "depi-bigote",
      name: "Bigote",
      desc: "Depilación rápida de la zona del bozo.",
      duration: "10 min",
      durationMinutes: 10,
      price: "$5.000",
      priceAmount: 5000,
    },
    {
      id: "depi-bozo-menton",
      name: "Bozo / bigote y mentón",
      desc: "Depilación de bozo y mentón con acabado cuidado.",
      duration: "15 min",
      durationMinutes: 15,
      price: "$11.500",
      priceAmount: 11500,
    },
  ],
};
