/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperacionesRouteImport } from './routes/operaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaTokenRouteImport } from './routes/reserva.$token'

const OperacionesRoute = OperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaTokenRoute = ReservaTokenRouteImport.update({
  id: '/reserva/$token',
  path: '/reserva/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operaciones': typeof OperacionesRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operaciones': typeof OperacionesRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operaciones': typeof OperacionesRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/operaciones' | '/reserva/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/operaciones' | '/reserva/$token'
  id: '__root__' | '/' | '/operaciones' | '/reserva/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperacionesRoute: typeof OperacionesRoute
  ReservaTokenRoute: typeof ReservaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operaciones': {
      id: '/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof OperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$token': {
      id: '/reserva/$token'
      path: '/reserva/$token'
      fullPath: '/reserva/$token'
      preLoaderRoute: typeof ReservaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperacionesRoute: OperacionesRoute,
  ReservaTokenRoute: ReservaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
