/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as OperacionesRouteImport } from './routes/operaciones'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as ReservaTokenRouteImport } from './routes/reserva.$token'
import { Route as PanelMasRouteImport } from './routes/panel/mas'
import { Route as PanelModuloIndexRouteImport } from './routes/panel/$modulo/index'
import { Route as PanelModuloSeccionRouteImport } from './routes/panel/$modulo/$seccion'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesRoute = OperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const ReservaTokenRoute = ReservaTokenRouteImport.update({
  id: '/reserva/$token',
  path: '/reserva/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelMasRoute = PanelMasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModuloIndexRoute = PanelModuloIndexRouteImport.update({
  id: '/$modulo/',
  path: '/$modulo/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModuloSeccionRoute = PanelModuloSeccionRouteImport.update({
  id: '/$modulo/$seccion',
  path: '/$modulo/$seccion',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/panel': typeof PanelRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/panel/mas': typeof PanelMasRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/$modulo/$seccion': typeof PanelModuloSeccionRoute
  '/panel/$modulo/': typeof PanelModuloIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/panel/mas': typeof PanelMasRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/panel': typeof PanelIndexRoute
  '/panel/$modulo/$seccion': typeof PanelModuloSeccionRoute
  '/panel/$modulo': typeof PanelModuloIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/panel': typeof PanelRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/panel/mas': typeof PanelMasRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/$modulo/$seccion': typeof PanelModuloSeccionRoute
  '/panel/$modulo/': typeof PanelModuloIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/operaciones'
    | '/panel'
    | '/privacidad'
    | '/panel/mas'
    | '/reserva/$token'
    | '/panel/'
    | '/panel/$modulo/$seccion'
    | '/panel/$modulo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/operaciones'
    | '/privacidad'
    | '/panel/mas'
    | '/reserva/$token'
    | '/panel'
    | '/panel/$modulo/$seccion'
    | '/panel/$modulo'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/operaciones'
    | '/panel'
    | '/privacidad'
    | '/panel/mas'
    | '/reserva/$token'
    | '/panel/'
    | '/panel/$modulo/$seccion'
    | '/panel/$modulo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  OperacionesRoute: typeof OperacionesRoute
  PanelRoute: typeof PanelRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  ReservaTokenRoute: typeof ReservaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones': {
      id: '/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof OperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/reserva/$token': {
      id: '/reserva/$token'
      path: '/reserva/$token'
      fullPath: '/reserva/$token'
      preLoaderRoute: typeof ReservaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/mas': {
      id: '/panel/mas'
      path: '/mas'
      fullPath: '/panel/mas'
      preLoaderRoute: typeof PanelMasRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/$modulo/': {
      id: '/panel/$modulo/'
      path: '/$modulo'
      fullPath: '/panel/$modulo/'
      preLoaderRoute: typeof PanelModuloIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/$modulo/$seccion': {
      id: '/panel/$modulo/$seccion'
      path: '/$modulo/$seccion'
      fullPath: '/panel/$modulo/$seccion'
      preLoaderRoute: typeof PanelModuloSeccionRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelMasRoute: typeof PanelMasRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelModuloSeccionRoute: typeof PanelModuloSeccionRoute
  PanelModuloIndexRoute: typeof PanelModuloIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelMasRoute: PanelMasRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelModuloSeccionRoute: PanelModuloSeccionRoute,
  PanelModuloIndexRoute: PanelModuloIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  OperacionesRoute: OperacionesRoute,
  PanelRoute: PanelRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  ReservaTokenRoute: ReservaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
