/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as OperacionesRouteImport } from './routes/operaciones'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaTokenRouteImport } from './routes/reserva.$token'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesRoute = OperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaTokenRoute = ReservaTokenRouteImport.update({
  id: '/reserva/$token',
  path: '/reserva/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/operaciones': typeof OperacionesRoute
  '/privacidad': typeof PrivacidadRoute
  '/reserva/$token': typeof ReservaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/operaciones'
    | '/privacidad'
    | '/reserva/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/operaciones' | '/privacidad' | '/reserva/$token'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/operaciones'
    | '/privacidad'
    | '/reserva/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  OperacionesRoute: typeof OperacionesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReservaTokenRoute: typeof ReservaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones': {
      id: '/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof OperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$token': {
      id: '/reserva/$token'
      path: '/reserva/$token'
      fullPath: '/reserva/$token'
      preLoaderRoute: typeof ReservaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  OperacionesRoute: OperacionesRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReservaTokenRoute: ReservaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
